### PR TITLE
Bundle improvements

### PR DESCRIPTION
**Pull request by vinicius73**
This PR follows changes made in https://github.com/nextcloud/nextcloud-event-bus/pull/481 and https://github.com/nextcloud/nextcloud-auth/pull/408

Related: #151 

- Update dependencies
- Add node test workflow
- Use rollup as bundler
  - Generate commonjs and ESM bundle compatible.
- Remove babel
  - Typescript already is able to generate code that is in compliance with es5

### CODE REVIEW

**Comment by vinicius73** [comment]
Waiting for next release of 
- https://www.npmjs.com/package/@nextcloud/event-bus
- https://www.npmjs.com/package/@nextcloud/auth

**Review by CarlSchwan — APPROVED** [review]

**Comment by juliushaertl** [comment]
@vinicius73 Mind to add the release action right away?

**Comment by juliushaertl** [comment]
Well never mind it is already there :)

**Review by juliushaertl — APPROVED** [review]

**Comment by vinicius73** [comment]
> @vinicius73 Mind to add the release action right away?

Sure

**Pull request merged**
