### PR TITLE
chore: Prepare 2.4.0 release

### LINKED ISSUE #627: Release 2.4
@ChristophWurst do you think we can prepare a 2.4 release (or a new 2.4 RC)?
I would appreciate to have the latest fixes released :)

### PR DESCRIPTION
**Pull request by susnux**
* Resolves #627 

If accepted, can someone with admin permission create the GH release to trigger the NPM release?

---

### Fixed
- Fix package exports to allow Typescript projects with module
  resolution of `Node16` or `NodeNext` to import the package

### Changed
- Axios upgrade from v0.27 to v1.4
- Update node engines to next LTS (node 20 / npm 9) 
- Dependency updates

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
lock file changes are suspicios

**Review by ChristophWurst — DISMISSED** [review]
wrong button

**Comment by skjnldsv** [comment]
> lock file changes are suspicios

Nah, it's because the lockfile version changed from 2 to 3 :+1:

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
> If accepted, can someone with admin permission create the GH release to trigger the NPM release?

@skjnldsv  / @ChristophWurst ?

**Comment by skjnldsv** [comment]
> > If accepted, can someone with admin permission create the GH release to trigger the NPM release?
> 
> @skjnldsv / @ChristophWurst ?

You now have permissions

**Pull request merged**
